### ISSUE TITLE
Nyromodal hidden behind JQuery slideshow

### ISSUE THREAD

**Issue by nhawrylyshyn** [nyroDev/nyroModal#138]
Hi, my page is using both nyromodal and jquery slideshow (http://jquery.malsup.com/cycle/). The issue I am having is that the nyromodal pop up is showing behind the slideshow always when I would like it to be infront of.

A snippet of page is at :  http://www.simplyhealthyliving.net/nyroTest.htm  , clicking the join mailing list brings up nyromodal behind the slideshow. 

I've tried googling this a fair bit but cannot find a solution, would appreciate any advice. The closest I came was for flash and nyroModal : http://www.captaindebug.com/2011/10/flash-flowplayer-and-nyromodal-overlays.html.

Thanks.

**Comment by flatsteve** [comment]
Hi there, 

I had a similar issue using the slides.js plug-in. I found that the issue was being caused by the slides div having a a large z-index is the CSS. Once I set the z-index to 0, the modal box appeared as it should - above the div. 

I would try setting the z-index of your slide-show to 0 or a low value. 

Hope this helps, Stephen.

**Comment by nyroDev** [comment]
To fix that, Update the nyroModal CSS file to add z-index above the one used in the slideshow.
You should add it on .nyroModalBg, .nyroModalCont and .nyroModalReposition
