### ISSUE TITLE
Post data from 'Submit form' over textEditor

### ISSUE THREAD

**Issue by ldt2008** [nyroDev/nyroModal#143]
Hello guy,
I use nyroModal for my apps (ASP.MVC) and i have an issue as follows

When i post data from Form, NyroModal only post data from textEditor don't post data from other control ex: (button)

Please help me, thanks

**Comment by kano2011** [comment]
Can you provide a code snippet of how to post data from textEditor?

**Comment by nyroDev** [comment]
This is a well known issue where the input submit button value is not sent.
This is because the bind is done on the form submit event, not the click event on the submit button.
To fix that, simply bind an event on the click of the submit button, add an input type hidden element on your form and let the submit event occurs.
