### ISSUE TITLE
Basic setup problem - image links just open the images

### ISSUE THREAD

**Issue by Tagbert** [nyroDev/nyroModal#165]
I'm trying to get started with nyroModel, but am stuck right from the start.

I have a series of anchors <a class="nyromodal" href="someimage" >
When I click on them, nyroModel does not appear, the browser just loads the image directly.

I am loading jquery.nyroModal.js and css file.
I enable it with $('.nyroModal').nyroModal(); loaded at the end of the document.

No matter what I do, all clicks just open the image directly.  (FF10 & Chrome)

This url is a simple example based on one of your demos. It doesn't work either. Any suggestions?
http://dl.dropbox.com/u/2186143/prototype/nyrotest.htm

**Comment by nyroDev** [comment]
nyroModal now requires jQuery 1.7 : you're using jQuery 1.4

If you executed youre page you should have seen the error: "$(".nyroModal").nyroModal is not a function"
This is because you're executing this function too early.
In order to execute it, use the following:
$(function() {
$(".nyroModal").nyroModal();
});

This will be executed once everything is loaded (king of a DOM load you try to add in your page.)
