### ISSUE TITLE
Problem with www

### ISSUE THREAD

**Issue by vamsikrishna6** [nyroDev/nyroModal#166]
when i enter url without www i'm getting problem with nyromodal. you can check the site www.introcare.com. For login/signup i've used nyromodal, it's working fine if url is given as www.introcare.com but getting problem when i enter url as introcare.com. The view page is loading with home page insted of login/signup pages.

I don't understand why it's happening.

**Comment by nyroDev** [comment]
www.introcare.com and introcare.com are not the same domain name. One has a subdomain (www) when the other doesn't.

That's why, when using introcare.com nyroModal load it through an iframe. And your website isn't designed to respond to normal request (ie not done through ajax) to render your login form: http://www.introcare.com/login

So, to fix your problem, I would highly recommand to automatically redirect the user to your www domain. It will be better for your SEO and for your scripts.

If you can't, you could also:
- Don't use absolute URL for your internal URLs
- Make you"'re website render only the form when request http://www.introcare.com/login (very bad solution)
