### ISSUE TITLE
Close Image Icon get cut off slightly - issue

### ISSUE THREAD

**Issue by WebPhenom** [nyroDev/nyroModal#167]
When we open a modal that is pulling data from another page, and we close the model using the image icon at the top right, when the modal fades out., the image button, the part that overlaps the border of the modal, gets cut out briefly as it closes. Hard to explain this so here is a like to see what I mean:  https://wwwdev.tmcc.edu/dev/modal.png  Any ideas what the fix might be? Thanks.

**Comment by llahnoraa** [comment]
I've noticed the same issue too.

**Comment by nyroDev** [comment]
This is a know issue, due to the way the closing animation are done.
To avoid bigger visual issue than this one, We have to set an overflow hidden on the .nyroModalCont, where the close button is added.
I can't give you a fix.
The thing we can do is simply hide the button, was we don't need it on the closing event...
