### ISSUE TITLE
jQuery isn't working within nyroModal pop-up

### ISSUE THREAD

**Issue by RoelofS** [nyroDev/nyroModal#194]
Hi,

I'm using nyroModal to create nice windows in my application. (online agenda).
The problem is, that jQuery isn't working within those windows. No datepicker, no fancy textarea (tinyMCE), nothing.

Is this normal behaviour? Couldn't find anything about it. Well, one topic, but it was closed without any answer.

Thanks in advance!

Best regards,

Roelof S

**Comment by mgasparel** [comment]
I'm assuming you are calling your datepickers etc... using $(document).ready(...)

The problem is that the content you are loading into the modal window isn't present when $(document).ready() fires.

You will need to use a callback function to rig your form elements after the modal window opens ie:
callbacks: {
    afterShowCont: function(nm) {
        $("#date").datepicker();
    }
}

**Comment by RoelofS** [comment]
Thanks man! Will try it!

**Comment by nyroDev** [comment]
As mgasparel said, you should use the afterShowCont callback to init yur datepicker and stuff like that.

If you're using script tags in the loaded page, you can also also add a rev="shown" attribute to your script tag.
Doing so will execute Javascript only when the modal is shown.
