### ISSUE TITLE
Video Keeps Playing After Modal is Closed - Firefox

### ISSUE THREAD

**Issue by markrichter** [nyroDev/nyroModal#219]
In Firefox 20.0 (PC and Mac), when clicking the video thumb in the right column of the site below, the video plays fine but when the modal window is closed, the video keeps playing - the only way I knew this was because the audio kept playing. If you click the thumbnail to launch the modal again, the video is still playing. This did not happen in older versions of FF - specifically I was able to re-create that it did NOT happen in 19.0.2. 

http://www.travelhq.com/cp/ctsDemo/index.html

**Comment by nyroDev** [comment]
This is an iframe.
Nyromodal copy the DOM element to show it on the modal.
Once it's closed, the DOM element is copy back where it was at the beggining.

In order to fix this, you'll have to write something by yourself to remove and rewrite the domelement as it was before (with a clone function for exemple)
