### ISSUE TITLE
how to use filter Iframe

### ISSUE THREAD

**Issue by davidportella** [nyroDev/nyroModal#28]
i try:
$('.nyroModal').nyroModal(filters:[Iframe]);
and
$('.nyroModal').nyroModal().nmFilters(Iframe);
and
$.nmFilters(Iframe);
$('.nyroModal').nyroModal();

It does not work, if you could give me an example of how to use it please.

PD: previously added "type: iframe" in settings

**Comment by batonmedia** [comment]
You should use single quotation marks:

$('.nyroModal').nyroModal(filters:['Iframe']);

**Comment by nyroDev** [comment]
single or double quote won't change.
For now, there is no ability to force filters manually.

**Comment by wilkerlucio** [comment]
there is no way to use an iframe modal by calling nmManual? Im really needing it...

**Comment by nyroDev** [comment]
Update documentation in Readme file
Add swfObjectId settings and use it in filters.swf or create an uniq ID. Closed by 3fafa309866755b1397617bae595353c276a4a88
Add recalc settings for nm.resize function to force the recalculation of the modal. Closed by 3fafa309866755b1397617bae595353c276a4a88 Closed by 3fafa309866755b1397617bae595353c276a4a88
Fix issue with jQuery 1.5 on IE8 (bogus selector in filters.swf). Closed by 3fafa309866755b1397617bae595353c276a4a88
Fix stack error when reopening a modal. Closed by 3fafa309866755b1397617bae595353c276a4a88
Add initFilters callbacks in order to force filters. Closed by 3fafa309866755b1397617bae595353c276a4a88 Closes#37
Add afterReposition and afterUnreposition callbacks.
