### ISSUE TITLE
V2 not working with Jquery 1.5 on IE8

### ISSUE THREAD

**Issue by lightjuice** [nyroDev/nyroModal#34]
I loaded the latest jquery from googleapis and could not work out why it was failing on IE8 until I looked at the jquery versions. I downgraded from JQ 1.5 to 1.4.4 and all is fine.

All was fine with JQ 1.5 on Chrome and FF

**Comment by sgsweb** [comment]
I had some issues also in the beginning.  You should make sure that you have the right DOCTYPE as follows:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

This might be the fix for you.

**Comment by mountaincoder** [comment]
We had the same problem and the DOCTYPE had no impact on it.

**Comment by nyroDev** [comment]
Update documentation in Readme file
Add swfObjectId settings and use it in filters.swf or create an uniq ID. Closed by 3fafa309866755b1397617bae595353c276a4a88
Add recalc settings for nm.resize function to force the recalculation of the modal. Closed by 3fafa309866755b1397617bae595353c276a4a88 Closed by 3fafa309866755b1397617bae595353c276a4a88
Fix issue with jQuery 1.5 on IE8 (bogus selector in filters.swf). Closed by 3fafa309866755b1397617bae595353c276a4a88
Fix stack error when reopening a modal. Closed by 3fafa309866755b1397617bae595353c276a4a88
Add initFilters callbacks in order to force filters. Closed by 3fafa309866755b1397617bae595353c276a4a88 Closes#37
Add afterReposition and afterUnreposition callbacks.

**Comment by mindbodyheart09** [comment]
OK. Don't put anything before the statement "<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">". Not even a space. I took the hard way to find it. ;-(
