### ISSUE TITLE
Autoresize nyromodal

### ISSUE THREAD

**Issue by stfr** [nyroDev/nyroModal#46]
Hello,
The resize() function doesn't autoresize the nyromodal, but seems to use the sizes.initH & sizes.initW parameters. It doesn't recalculated size with the current nyroModal content.

**Comment by nyroDev** [comment]
Update documentation in Readme file
Add swfObjectId settings and use it in filters.swf or create an uniq ID. Closed by 3fafa309866755b1397617bae595353c276a4a88
Add recalc settings for nm.resize function to force the recalculation of the modal. Closed by 3fafa309866755b1397617bae595353c276a4a88 Closed by 3fafa309866755b1397617bae595353c276a4a88
Fix issue with jQuery 1.5 on IE8 (bogus selector in filters.swf). Closed by 3fafa309866755b1397617bae595353c276a4a88
Fix stack error when reopening a modal. Closed by 3fafa309866755b1397617bae595353c276a4a88
Add initFilters callbacks in order to force filters. Closed by 3fafa309866755b1397617bae595353c276a4a88 Closes#37
Add afterReposition and afterUnreposition callbacks.
