### ISSUE TITLE
$.ajax settings

### ISSUE THREAD

**Issue by ghost** [nyroDev/nyroModal#61]
For my projects I have the $.ajaxSettings set to do something for beforeSend and my dataType is 'json'.  nyroModal requires the dataType to be html and if beforeSend has something in it, you have a progress bar running in the background.  May I recommend that you hard code 

beforeSend:function() { },
dataType:'html',

into the source code so that nyroModal works no matter what the person does to their ajaxSettings.  Looks like around line 1131 and 1132

**Comment by nyroDev** [comment]
I won't do that for many reason.
The biggest one is that there is multiple time where ajax request are done, and not only in link filter.
It's the duty to the developper to update his beforeSend and other ajax stuff like that in order to make nyroModal works.

BTW, thanks for your report and usggestion.
