### ISSUE TITLE
nmManual Iframe problem

### ISSUE THREAD

**Issue by jasne** [nyroDev/nyroModal#74]
Hi,

In nyroModal v2.0.0 is some problem when i try to set iframe by nmManual:

my code:

 $.nmManual('url','iframe');

**Comment by nyroDev** [comment]
$.nmManual function is not all intended to be used this way, regarding the second argument.
Second argument should be a json object of settings, to parameter the modal.

In order to force the iframe filter, you should do something like:
$.nmManual('url', {
  callbacks: {
    initFilters: function(nm) {
      nm.filters.push('link');
      nm.filters.push('iframe');
    }
  }
});

And it might work.
I didn't test it, so please let me know.
