### ISSUE TITLE
when content in modal box changes, the box does not resize

### ISSUE THREAD

**Issue by jethroma** [nyroDev/nyroModal#9]

**Comment by nyroDev** [comment]
Yes, that's normal.
To resize the modal, you can use:

$.nmTop().resize();

Please let me know if it works as expected.

**Comment by jethroma** [comment]
Hi, this does not resize the modal box.

I am creating a model with $.nmManual('login.php', {stack: false});
Then using some ajax to login, if login fails append an error message which appends to the content of the box... but $.nmTop.resize(); doesn't resize the box to fit the new content.

**Comment by nyroDev** [comment]
Update documentation in Readme file
Add swfObjectId settings and use it in filters.swf or create an uniq ID. Closed by 3fafa309866755b1397617bae595353c276a4a88
Add recalc settings for nm.resize function to force the recalculation of the modal. Closed by 3fafa309866755b1397617bae595353c276a4a88 Closed by 3fafa309866755b1397617bae595353c276a4a88
Fix issue with jQuery 1.5 on IE8 (bogus selector in filters.swf). Closed by 3fafa309866755b1397617bae595353c276a4a88
Fix stack error when reopening a modal. Closed by 3fafa309866755b1397617bae595353c276a4a88
Add initFilters callbacks in order to force filters. Closed by 3fafa309866755b1397617bae595353c276a4a88 Closes#37
Add afterReposition and afterUnreposition callbacks.
